name: container-toolkit Check

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  check_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

    - name: Check versions
      run: |
        LATEST_TOOLKIT="$(curl -s https://api.github.com/repos/NVIDIA/nvidia-container-toolkit/releases/latest | jq -r '.tag_name' | sed 's/^v//')"
        CURRENT_TOOLKIT="$(curl -s https://api.github.com/repos/unraid/nvidia-container-toolkit/releases/latest | jq -r '.tag_name' | sed 's/^v//')"

        if ! echo "${LATEST_TOOLKIT}" | grep -qE '^[0-9]+(\.[0-9]+)*$'; then
          echo "Can't get latest version"
          exit 1
        fi

        if ! echo "${CURRENT_TOOLKIT}" | grep -qE '^[0-9]+(\.[0-9]+)*$'; then
          echo "Can't get current version"
          exit 1
        fi

        if [ "${LATEST_TOOLKIT}" != "${CURRENT_TOOLKIT}" ]; then
          echo "CREATE_RELEASE=true" >> $GITHUB_ENV
          echo "TOOLKIT_VERSION=${LATEST_TOOLKIT}" >> $GITHUB_ENV
        else
          echo "Up to date!"
          echo "CREATE_RELEASE=false" >> $GITHUB_ENV
        fi

    - name: Log in to GitHub Container Registry
      if: env.CREATE_RELEASE == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Docker container and build toolkit
      if: env.CREATE_RELEASE == 'true'
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/output:/tmp \
          -e TOOLKIT_VERSION=${TOOLKIT_VERSION} \
          ghcr.io/unraid/nvidia-container-toolkit:buster

    - name: Create Release
      if: env.CREATE_RELEASE == 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TOOLKIT_VERSION }}
        name: nvidia-container-toolkit v${{ env.TOOLKIT_VERSION }}
        files: |
          ./output/v${{ env.TOOLKIT_VERSION }}/nvidia-container-toolkit-v${{ env.TOOLKIT_VERSION }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Dummy commit (keep workflow alive)
      if: env.CREATE_RELEASE == 'false'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit --allow-empty -m "Keep GH Action alive"
        git push
